using Sufni.App.ExtensionHost.Contracts.Capabilities;

namespace Sufni.App.ExtensionHost.Contracts.RecordedSessions;

public interface IRecordedSessionToolbarContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionPageContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionMediaPaneContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionStatisticsBannerContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionStatisticsOverlayContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionStatisticsTabContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionListIndicatorContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionListActionContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionHostedGraphRowContributionViewModel : IExtensionViewModel;
