using Sufni.App.ExtensionHost.Contracts.Capabilities;

namespace Sufni.App.ExtensionHost.Contracts.RecordedSessions;

public interface IRecordedSessionToolbarContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionPageContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionMediaPaneContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionAnalysisBannerContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionAnalysisOverlayContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionAnalysisTabContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionListIndicatorContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionListActionContributionViewModel : IExtensionViewModel;

public interface IRecordedSessionHostedSignalRowContributionViewModel : IExtensionViewModel;
